spring:
  config:
    import: optional:file:.env.properties

  application:
    name: ComplianceReturnsTracking

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

server:
  port: 18000
  servlet:
    context-path: "/"

azure:
  tenant-id: ${AZURE_TENANT_ID}
  client-id: ${AZURE_CLIENT_ID}
  client-secret: ${AZURE_CLIENT_SECRET}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

system:
  admin:
    username: ${SYSTEM_ADMIN_USERNAME}
    password: ${SYSTEM_ADMIN_PASSWORD}
    email: ${SYSTEM_ADMIN_EMAIL}
    user:
      default-password: ${SYSTEM_DEFAULT_PASSWORD}

cors:
  allowed-origins:
    - http://localhost:3000
    - http://127.0.0.1:3000

app:
  encryption:
    secret-key: ${ENCRYPTION_SECRET_KEY}
  registration:
    allowed:
      email-domains:
        - nbs.co.zw
  default-department:
    name: ICT
    hod-email: ${SYSTEM_ADMIN_EMAIL}
    escalation-email: ${SYSTEM_ADMIN_EMAIL}
  storage:
    dir: ./uploads/
    archived: ./archived/
    max-file-size: 10485760
    allowed-file-types:
      - application/pdf
      - image/jpeg
      - image/png
      - text/plain

mail:
  host: ${MAIL_HOST}
  port: ${MAIL_PORT}
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  from: ${MAIL_FROM}

spring.mail.from: ${MAIL_FROM}

email:
  approval:
    message: "'{0}' has been uploaded and awaits your approval."
  verified:
    message: "'{0}' has been verified."
  rejected:
    message: "'{0}' was rejected."

token:
  reset:
    expiration: 1440

user:
  forgot:
    password:
      url: "http://localhost:3000/auth/change-password/"
  account:
    creation:
      url: "http://localhost:3000/auth/set-password/"

superadmin:
  role: ROLE_SUPER_SYSTEM_ADMIN